---
- name: Deploy Services with Docker Compose
  hosts: 127.0.0.1
  gather_facts: false

  tasks:
    - name: Install Docker and Docker Compose
      become: true
      apt:
        name: ['docker.io', 'docker-compose']
        state: present

    - name: Start Docker service
      become: true
      service:
        name: docker
        state: started

    - name: Copy Docker Compose file to the server
      copy:
        src: ./docker-compose.yml
        dest: /home/user/docker-compose.yml
        remote_src: yes
      become: true

    - name: Run Docker Compose
      become: true
      command: docker-compose -f /home/user/docker-compose.yml up -d
      args:
        chdir: /home/user
