version: '3.8'

services:
  api:
    build:
      context: ./docker_images/api
    env_file: 
      - ./.env
    restart: always
    container_name: api-car
    ports:
      - 3001:3001

  web:
    build:
      context: ./docker_images/web
    env_file:
      - ./docker_images/web/files/.env.local
    restart: always
    container_name: front-car
    ports:
      - "3000:3000"
    depends_on:
      - api

    
